name: merchok
# description: "A new Flutter project."
publish_to: 'none'
version: 0.2.2-dev

environment:
  sdk: ^3.9.0

dependencies:
  collection: ^1.19.1
  csv: ^6.0.0
  dotted_border: ^3.1.0
  equatable: ^2.0.7
  file_picker: ^10.3.3
  file_saver: ^0.3.1
  fl_chart: ^1.1.1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  flutter_spinkit: ^5.2.2
  flutter_svg: ^2.2.1
  fluttertoast: ^9.0.0
  get_it: ^8.2.0
  go_router: ^16.2.4
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  image: ^4.5.4
  image_picker: ^1.2.0
  intl: ^0.20.2
  markdown_widget: ^2.3.2+8
  package_info_plus: ^9.0.0
  provider: ^6.1.5+1
  shared_preferences: ^2.5.3
  skeletonizer: ^2.1.0+1
  talker_bloc_logger: ^5.0.1
  talker_flutter: ^5.0.1
  url_launcher: ^6.3.2
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.13

flutter:
  uses-material-design: true

  assets:
    - assets/docs/privacy_policy/
    - assets/docs/terms_conditions/
    - assets/icons/
    - assets/icons/banks/
    - assets/images/

  fonts:
    - family: Merchok
      fonts:
        - asset: assets/fonts/Merchok-Icons.ttf
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Thin.ttf
          weight: 100
        - asset: assets/fonts/Montserrat-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Montserrat-Black.ttf
          weight: 900
          
flutter_intl:
  enabled: true
