// c:\Codes\merchok\lib\features\stock\domain\repositories.dart exports
// generated by: https://marketplace.visualstudio.com/items?itemName=elmsec.dart-flutter-exports:


export 'stock_repository.dart';