// c:\Codes\merchok\lib\features\festival\domain\repositories.dart exports
// generated by: https://marketplace.visualstudio.com/items?itemName=elmsec.dart-flutter-exports:


export 'festival_repository.dart';