// c:\Codes\merchok\lib\features\festival\data\repositories.dart exports
// generated by: https://marketplace.visualstudio.com/items?itemName=elmsec.dart-flutter-exports:


export 'festival_repository_impl.dart';