// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCER8npgeXV5MijYAzWo0QYG0Y2mnx_kxA',
    appId: '1:496138794888:web:519577f8011e60c981ec3d',
    messagingSenderId: '496138794888',
    projectId: 'merchok-gd',
    authDomain: 'merchok-gd.firebaseapp.com',
    storageBucket: 'merchok-gd.firebasestorage.app',
    measurementId: 'G-NEY80W1GF5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCk_sqB_oviS79brLaxx36oLY7OkhHq80Y',
    appId: '1:496138794888:android:58984485f523835a81ec3d',
    messagingSenderId: '496138794888',
    projectId: 'merchok-gd',
    storageBucket: 'merchok-gd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXvQXwBDMxMDO8Z4lXmcTqnVVUXwGXlLQ',
    appId: '1:496138794888:ios:6d4e0eff8e67b15581ec3d',
    messagingSenderId: '496138794888',
    projectId: 'merchok-gd',
    storageBucket: 'merchok-gd.firebasestorage.app',
    iosBundleId: 'com.gastdash.merchok',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXvQXwBDMxMDO8Z4lXmcTqnVVUXwGXlLQ',
    appId: '1:496138794888:ios:6d4e0eff8e67b15581ec3d',
    messagingSenderId: '496138794888',
    projectId: 'merchok-gd',
    storageBucket: 'merchok-gd.firebasestorage.app',
    iosBundleId: 'com.gastdash.merchok',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCER8npgeXV5MijYAzWo0QYG0Y2mnx_kxA',
    appId: '1:496138794888:web:d5e1efaa3bf43f8c81ec3d',
    messagingSenderId: '496138794888',
    projectId: 'merchok-gd',
    authDomain: 'merchok-gd.firebaseapp.com',
    storageBucket: 'merchok-gd.firebasestorage.app',
    measurementId: 'G-EJJ73TLMJS',
  );
}
