// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:merchok/features/category/domain/entities/category.dart';
import 'package:merchok/features/festival/domain/entities/festival.dart';
import 'package:merchok/features/merch/domain/entities/merch.dart';
import 'package:merchok/features/orders/domain/entities/order.dart';
import 'package:merchok/features/orders/domain/entities/order_item.dart';
import 'package:merchok/features/payment_method/domain/entities/payment_method.dart';
import 'package:merchok/features/stock/domain/entities/stock_item.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(CategoryAdapter());
    registerAdapter(FestivalAdapter());
    registerAdapter(MerchAdapter());
    registerAdapter(OrderAdapter());
    registerAdapter(OrderItemAdapter());
    registerAdapter(PaymentMethodAdapter());
    registerAdapter(StockItemAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(CategoryAdapter());
    registerAdapter(FestivalAdapter());
    registerAdapter(MerchAdapter());
    registerAdapter(OrderAdapter());
    registerAdapter(OrderItemAdapter());
    registerAdapter(PaymentMethodAdapter());
    registerAdapter(StockItemAdapter());
  }
}
